### PR TITLE
Feature/check in refactor

### PR DESCRIPTION
**Pull request by Rethakgetse-Manaka**
# Description

Refactored Check in and got the other functions to work as expected. I had to refactor check in so that it can match the coding standards and I also abstracted certain functionalities to their own functions.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Testing is not working as it should
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Testing is not working properly, I'll return back to it to write proper unit tests for now I am moving onto other functions and documentation for the sake of time

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by waveyboym** [comment]
@Rethakgetse-Manaka , I would just like to ask you if you could please ensure that all actions are passing before you merge your related branch into develop🙂👍. Thanks👌!

**Comment by waveyboym** [comment]
also, @Rethakgetse-Manaka could you consider updating this file: https://github.com/COS301-SE-2024/occupi/blob/develop/documentation/occupi-docs/pages/api-documentation/api-usage.mdx with the new api endpoints you have created, like what the expected json object, and possible success an/or failure responses as the frontend needs it

**Comment by Rethakgetse-Manaka** [comment]
Yeah I am planning on doing the updates today alongside the other documentation I am doing

**Comment by Rethakgetse-Manaka** [comment]
The fail was because of it saying is undefined but when I checked the middleware file c is defined but I'll take note of that

**Comment by waveyboym** [comment]
> The fail was because of it saying is undefined but when I checked the middleware file c is defined but I'll take note of that

yeah I saw, perhaps I may have left that c in there mistakenly, not sure how because everything was passing beforehand, but nevertheless, I fixed it, it just needed to be changed from ```c``` to ```ctx```. But if you need some help figuring out something, don't hesitate to send me a message and I'll come help you ASAP👍

**Pull request merged**
